version: "3.8"

services:
    # PHP-FPM Service
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile
        container_name: api
        networks:
            - eccomerce
        working_dir: /var/www/api
        tty: true
        restart: unless-stopped
        volumes:
            - ./api:/var/www/api
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db
    
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8100:80"
            - "8143:443"
        volumes:
            - ./api:/var/www/api
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - eccomerce
    
    # Postgres - Service
    db:
        build: ./db
        container_name: postgres
        restart: unless-stopped
        tty: true
        networks:
            - eccomerce
        volumes:
            - postgresdata:/var/lib/postgresql/data
        ports:
            - "3306:5432"

volumes:
    postgresdata:
        driver: local

networks:
    eccomerce:
        driver: bridge